[package]
name = "task-cli"
version = "0.1.0"
edition = "2021"
author = "Goitseone Themba"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
chrono = { version = "0.4.38", features = ["serde"] }
chrono-tz = "0.10.0"
